<?php

namespace Database\Seeders;

use App\Models\Branch;
use App\Models\Product;
use App\Models\ProductVariant;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Seeds products and variants from products_export_2026-04-08.csv.
 *
 * CSV columns: Product Name, SKU, Variant (Weight/Size), Grade, Unit, Factory/Branch, Active Price (BDT), Price Effective Date
 *
 * Mapping:
 *   - Parent product  = product name stripped of "(XXkg)" suffix → products table
 *   - Variant         = one row per (product + weight + grade + branch) → product_variants table
 *   - Display name    = auto-generated by ProductVariant::buildDisplayName()
 */
class ProductCsvSeeder extends Seeder
{
    public function run(): void
    {
        $csvPath = base_path('../Downloads/products_export_2026-04-08.csv');

        if (! file_exists($csvPath)) {
            $this->command->error("CSV not found at: $csvPath");
            return;
        }

        // Pre-load branch name → id map (case-insensitive partial match)
        $branches = Branch::all()->keyBy(fn ($b) => strtolower($b->name));

        $rows = $this->parseCsv($csvPath);

        DB::transaction(function () use ($rows, $branches) {
            foreach ($rows as $row) {
                $csvProduct  = trim($row['Product Name']);
                $csvSku      = trim($row['SKU']);
                $csvWeight   = $this->normaliseWeight($row['Variant (Weight/Size)']);
                $csvGrade    = trim(strtoupper($row['Grade']));
                $csvUnit     = trim($row['Unit']) ?: 'kg';
                $csvBranch   = trim($row['Factory/Branch']);
                $csvPrice    = (float) str_replace(',', '', $row['Active Price (BDT)']);
                $csvDate     = trim($row['Price Effective Date']);

                // Resolve branch
                $branchId = $this->resolveBranch($csvBranch, $branches);
                if (! $branchId) {
                    $this->command->warn("Branch not found: '$csvBranch' — skipping row.");
                    continue;
                }

                // Derive base product name: strip trailing "(XXkg)" or "( XXkg )"
                $baseProductName = preg_replace('/\s*\(\s*\d+\s*kg\s*\)\s*$/i', '', $csvProduct);
                $baseProductName = trim($baseProductName) ?: $csvProduct;

                // Upsert product
                $product = Product::firstOrCreate(
                    ['name' => $baseProductName],
                    ['unit' => $csvUnit, 'is_active' => true]
                );

                // Upsert variant (unique: product + weight + grade + branch)
                $variant = ProductVariant::where('product_id', $product->id)
                    ->where('weight_kg',  $csvWeight)
                    ->where('grade',      $csvGrade)
                    ->where('branch_id',  $branchId)
                    ->first();

                $variantData = [
                    'product_id'     => $product->id,
                    'sku'            => $csvSku ?: null,
                    'weight_kg'      => $csvWeight,
                    'grade'          => $csvGrade,
                    'branch_id'      => $branchId,
                    'unit'           => $csvUnit,
                    'price'          => $csvPrice,
                    'effective_date' => $csvDate ?: null,
                    'is_active'      => true,
                    'stock'          => 0,
                ];

                if ($variant) {
                    $variant->update($variantData);
                } else {
                    $variant = new ProductVariant($variantData);
                    $variant->save(); // triggers buildDisplayName() in boot
                }

                $this->command->line("  ✓ {$variant->name}  →  ৳{$csvPrice}");
            }
        });

        $this->command->info('CSV import complete.');
    }

    private function parseCsv(string $path): array
    {
        $rows    = [];
        $handle  = fopen($path, 'r');
        $headers = null;

        while (($line = fgetcsv($handle)) !== false) {
            if ($headers === null) {
                $headers = array_map('trim', $line);
                continue;
            }
            if (count($line) !== count($headers)) continue;
            $rows[] = array_combine($headers, $line);
        }

        fclose($handle);
        return $rows;
    }

    private function normaliseWeight(string $raw): float
    {
        $raw = trim($raw);
        // If it's a plain number, use it directly (handles "50", "74", "100", etc.)
        if (is_numeric($raw)) {
            $w = (float) $raw;
            // The Sunflower SP (50kg) was erroneously exported with weight=100
            // Correct it back to 50
            return $w === 100.0 ? 50.0 : $w;
        }
        // e.g. "RUTI MOIDA (74KG)" — extract number
        if (preg_match('/(\d+(?:\.\d+)?)/i', $raw, $m)) {
            return (float) $m[1];
        }
        return 0.0;
    }

    private function resolveBranch(string $csvBranch, \Illuminate\Support\Collection $branches): ?int
    {
        $lower = strtolower(trim($csvBranch));

        // Direct match
        foreach ($branches as $key => $branch) {
            if ($key === $lower || str_contains($key, $lower) || str_contains($lower, explode(' ', $key)[0])) {
                return $branch->id;
            }
        }
        return null;
    }
}
